package com.expenses.model;

// Generated Jan 8, 2014 3:15:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ExpenseUser generated by hbm2java
 */
@Entity
@Table(name = "expense_user", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class ExpenseUser implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private Set<Expense> expenses = new HashSet<Expense>(0);
	private Set<ExpenseUserRole> expenseUserRoles = new HashSet<ExpenseUserRole>(
			0);
	private Set<ExpenseCategory> expenseCategories = new HashSet<ExpenseCategory>(
			0);

	public ExpenseUser() {
	}

	public ExpenseUser(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public ExpenseUser(int id, String username, String password,
			Set<Expense> expenses, Set<ExpenseUserRole> expenseUserRoles,
			Set<ExpenseCategory> expenseCategories) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.expenses = expenses;
		this.expenseUserRoles = expenseUserRoles;
		this.expenseCategories = expenseCategories;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "expenseUser")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "expenseUser")
	public Set<ExpenseUserRole> getExpenseUserRoles() {
		return this.expenseUserRoles;
	}

	public void setExpenseUserRoles(Set<ExpenseUserRole> expenseUserRoles) {
		this.expenseUserRoles = expenseUserRoles;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "expenseUser")
	public Set<ExpenseCategory> getExpenseCategories() {
		return this.expenseCategories;
	}

	public void setExpenseCategories(Set<ExpenseCategory> expenseCategories) {
		this.expenseCategories = expenseCategories;
	}

}
