package com.expenses.model;

// Generated Dec 18, 2013 11:38:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "expense", schema = "public")
public class Expense implements java.io.Serializable {

	private int id;
	private ExpenseCategory expenseCategory;
	private String description;
	private Float cost;
	private Date entered;

	public Expense() {
	}

	public Expense(int id) {
		this.id = id;
	}

	public Expense(int id, ExpenseCategory expenseCategory, String description,
			Float cost, Date entered) {
		this.id = id;
		this.expenseCategory = expenseCategory;
		this.description = description;
		this.cost = cost;
		this.entered = entered;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category")
	public ExpenseCategory getExpenseCategory() {
		return this.expenseCategory;
	}

	public void setExpenseCategory(ExpenseCategory expenseCategory) {
		this.expenseCategory = expenseCategory;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cost", precision = 8, scale = 8)
	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entered", length = 13)
	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

}
