package com.expenses.model;

// Generated Dec 18, 2013 11:38:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExpenseCategory generated by hbm2java
 */
@Entity
@Table(name = "expense_category", schema = "public")
public class ExpenseCategory implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<Expense> expenses = new HashSet<Expense>(0);

	public ExpenseCategory() {
	}

	public ExpenseCategory(int id) {
		this.id = id;
	}

	public ExpenseCategory(int id, String name, String description,
			Set<Expense> expenses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.expenses = expenses;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "expenseCategory", cascade=CascadeType.ALL)
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}
}
