package com.expenses.model;

// Generated Jan 8, 2014 3:15:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExpenseUserRole generated by hbm2java
 */
@Entity
@Table(name = "expense_user_role", schema = "public")
public class ExpenseUserRole implements java.io.Serializable {

	private int id;
	private ExpenseUser expenseUser;
	private String role;

	public ExpenseUserRole() {
	}

	public ExpenseUserRole(int id, String role) {
		this.id = id;
		this.role = role;
	}

	public ExpenseUserRole(int id, ExpenseUser expenseUser, String role) {
		this.id = id;
		this.expenseUser = expenseUser;
		this.role = role;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public ExpenseUser getExpenseUser() {
		return this.expenseUser;
	}

	public void setExpenseUser(ExpenseUser expenseUser) {
		this.expenseUser = expenseUser;
	}

	@Column(name = "role", nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
